FROM ubuntu

# => Define variáveis de ambiente
ENV VALOR_DOCKER_ENV=1234567890 \
    NOME_VARIAVEL="Valor da Variável" \ 
    VARIAVEL_COM_ESPACO="Variável com Espaço em Branco" \   
    VARIAVEL_SEM_VALOR="" \
    VARIAVEIS_DUAS_LINHAS="Primeira linha\nSegunda linha" \ 