# => Cria a camada do Dockerfile
FROM ubuntu:latest

# => Adicona metadados na imagem
LABEL Image="Imagem  de Teste" \
      Author="Antonio Figueiredo" \
      Version="1.0" \
      Description="Essa é uma imagem para testes." \
      E-mail="profantonio.figueiredo@fiap.com"


