FROM ubuntu

# => Ajuda você a configurar um container que pode ser executado com um Executável
ENTRYPOINT [ "ECHO", "Hello World" ]

# Arquivo entrypoint.sh

# 

# Documentação da Docker:
# https://docs.docker.com/engine/reference/builder/#understand-how-cmd-and-entrypoint-interact