FROM ubuntu:18.04

RUN apt-get -y update

# Cria diretório  para o projeto e define o seu diretório corrente
WORKDIR /app-java

# Copia arquivos ou diretórios e adiona ao sistema de arquivos da imagem
ADD arquivo-host.json arquivo-host-transferido.json
ADD https://www.google.com pagina.html









